### ISSUE TITLE
Error in Line 310 of "SotaTool_mk3.py"

### ISSUE THREAD

**Issue by akfeeney** [steinjm/SotaTool#1]
Hello,

I submitted a file to the program that was imaged at 40X and stained for alpha-actinin in tiff format where the pixels per micron resolution is 0.16. I get an immediate error that pops up in the command line and shuts down the program without creating any output. The error message reads as follows:

Traceback (most recent call last):
      File "SotaTool_mk3.py", line 310, in <module>
ValueError: max() arg is an empty sequence
[12484] Failed to execute script "SotaTool_mk3" due to an unhandled exception!

Please let me know what the next best step would be! Thanks for your help in advance.

**Comment by steinjm** [comment]
Hi, 

Thanks for bringing this issue up. I'm pretty sure your 0.16 is actually the pixel size, not the pixel/micron resolution. Please input 6.25 (1/0.16) and retry. 

Kind regards,
Jeroen

**Comment by akfeeney** [comment]
Thanks so much. My error on not doing the conversion. The analysis worked well after changing that parameter and running the software with 4x4 segmentation.

Cheers,
Austin
